### ISSUE TITLE
Corrigé des fautes sur le tutoriel

### ISSUE THREAD

**Issue by alpha-server** [ChanalTanguy/StreetCar#22]
Correction des fautes présente sur les différentes diapositives du tutoriel.

**Comment by ChanalTanguy** [comment]
**Toutes les diapos**
- Un espace AVANT **ET** APRÈS chaque deux-points ":"
- Soit terminer par des points "." à chaque fois, soit les enlever tous

**Diapo 1**
- "Main Joueur 2" --> "Main du joueur 2"
- "Votre Joueur 1" --> "Main du Joueur 1"
- "Vos objectifs" --> "Objectifs du Joueur 1"
- "Poser des tuiles" --> "Posez des tuiles"
- "Appuyer" --> "Appuyez"
- "Appuyer sur un onglet pour aller à ce tour" --> "Appuyez sur un nombre pour aller au tour correspondant"
- "refaire le tour" --> "rejouer le tour"

**Diapo 2**
- "Votre but est de finir votre ligne" --> "Votre but est de compléter votre ligne"
- "les escales" --> "vos escales"

**Diapo 3**
- "deux tuiles par tour en suivant ces règles" --> "deux tuiles par tour, en suivant ces règles"
- "qui mène" --> "ne menant"

**Diapo 4**
- "Vous pouvez remplacer une tuile par" --> "Vous ne pouvez remplacer une tuile que par"
- "au moins tous les chemins" --> "chaque chemin"
- "que vous voulez remplacer" --> "à remplacer"

**Diapo 5**
- "de façon simultané" --> "de façon simultanée"
- "des chemins" --> "un chemin"

**Diapo 6**
- "en piochant avec" --> "en piochant avec :"

**Diapo 7**
- Image manquante
- Texte trop proche du bord droit
- "Lors du début" --> "En début"
- "vont vous être assignés" --> "vous sont assignées"
- "la case stop adjacente" --> "les cases Stop adjacentes"

**Diapo 8**
- "posé" --> "posée"
- "un stop" --> "un Stop"
- "les deux case stop" --> "les deux cases Stop"
